variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

gradle build: # Job name
  stage: build # Stage name
  image:
    name: docker.io/gradle:6.9.2-jdk8 # kaniko image 사용
    entrypoint: [""]
  script:
    - export
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - |
      if [[ ! -e gradle/wrapper/gradle-wrapper.jar ]]
      then
        gradle wrapper
      fi
    - chmod +x gradlew
    - ./gradlew build -x test
  cache: # Artifact tag 사용 가능
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradlew
