variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  REPOSITORY_USERNAME: ${PORTAL_TOKEN_NAME}
  REPOSITORY_PASSWORD: ${GROUP_CP_TOKEN}

  APP_NAME: "cp-portal-terraman"
  APP_VERSION: "1.4"
  IMAGE_TAGS: $CI_COMMIT_SHA

  SERVICE_PORT: "8091"
  SERVICE_TARGET_PORT: "8091"
  SERVICE_NODEPORT: "32707"

  SONAR_TOKEN: 7e63d6ff74e9b2be5a177a4eaa85dd09e3887272
  SONAR_HOST_URL: http://15.164.195.107:30087

  ENV_SCOPE: dev_aws
