variables:
  CONFIGMAP_NAME: cp-terraman-configmap
  CONFIGMAP_VERSION: "1.3"

  DATABASE_URL: "cp-mariadb.mariadb.svc.cluster.local:3306"
  DATABASE_USER_ID: cp-admin
  DATABASE_USER_PASSWORD: Paasta!2022
  DATABASE_TERRAMAN_ID: terraman
  DATABASE_TERRAMAN_PASSWORD: Paasta!2022
  KEYCLOAK_URL: "https://$K8S_MASTER_NODE_IP.nip.io:32710"
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_CP_REALM: cp-realm
  KEYCLOAK_DB_SCHEMA: keycloak
  CP_PORTAL_DB_SCHEMA: cpdev
  KEYCLOAK_CP_CLIENT_ID: cp-client
  KEYCLOAK_CP_CLIENT_SECRET: bfbc9f86-81f4-4307-b57e-c84e943a5bc5
  CP_SERVICE_PIPELINE_NAMESPACE: "cp-pipeline"
  CP_SERVICE_SOURCE_CONTROL_NAMESPACE: "cp-source-control"
  CP_DEFAULT_INGRESS_NAMESPACE: "ingress-nginx"
  NFS_NAMESPACE: nfs-storageclass
  REPOSITORY_NAMESPACE: harbor
  DATABASE_NAMESPACE: mariadb
  KEYCLOAK_NAMESPACE: keycloak
  VAULT_ROLE_NAME: webapp
  CP_PORTAL_PROVIDER_TYPE: cp-portal-$PROVIDER_TYPE
  CONFIGMAP_CHART_PATH: ./container-platform-helm-chart/container-platform-terraman/container-platform-terraman-configmap
  K8S_MASTER_HOST_KEY: master-host-key

configmap deploy:
  stage: pre-deploy
  needs: ["secret deploy"]
  image:
    name: alpine/k8s:1.19.15
    entrypoint: [""]
  script:
    - export
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${K8S_MASTER_NODE_IP}/$K8S_MASTER_NODE_IP/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${K8S_API_SERVER_PORT}/$K8S_API_SERVER_PORT/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${K8S_AUTH_BEARER_TOKEN}/$K8S_AUTH_BEARER_TOKEN/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s~\${KEYCLOAK_URL}~$KEYCLOAK_URL~g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s~\${KEYCLOAK_DB_SCHEMA}~$KEYCLOAK_DB_SCHEMA~g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s~\${CP_PORTAL_DB_SCHEMA}~$CP_PORTAL_DB_SCHEMA~g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_ADMIN_USERNAME}/$KEYCLOAK_ADMIN_USERNAME/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_ADMIN_PASSWORD}/$KEYCLOAK_ADMIN_PASSWORD/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_CP_REALM}/$KEYCLOAK_CP_REALM/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_CP_CLIENT_ID}/$KEYCLOAK_CP_CLIENT_ID/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_CP_CLIENT_SECRET}/$KEYCLOAK_CP_CLIENT_SECRET/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_URL}/$DATABASE_URL/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_USER_ID}/$DATABASE_USER_ID/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_USER_PASSWORD}/$DATABASE_USER_PASSWORD/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_TERRAMAN_ID}/$DATABASE_TERRAMAN_ID/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_TERRAMAN_PASSWORD}/$DATABASE_TERRAMAN_PASSWORD/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${CP_SERVICE_PIPELINE_NAMESPACE}/$CP_SERVICE_PIPELINE_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${CP_SERVICE_SOURCE_CONTROL_NAMESPACE}/$CP_SERVICE_SOURCE_CONTROL_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${CP_DEFAULT_INGRESS_NAMESPACE}/$CP_DEFAULT_INGRESS_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${NFS_NAMESPACE}/$NFS_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${REPOSITORY_NAMESPACE}/$REPOSITORY_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${DATABASE_NAMESPACE}/$DATABASE_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${KEYCLOAK_NAMESPACE}/$KEYCLOAK_NAMESPACE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${CP_PORTAL_PROVIDER_TYPE}/$CP_PORTAL_PROVIDER_TYPE/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${VAULT_IP}/$VAULT_IP/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${VAULT_PORT}/$VAULT_PORT/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${VAULT_ROLE_NAME}/$VAULT_ROLE_NAME/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${VAULT_ROLE_ID}/$VAULT_ROLE_ID/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${VAULT_SECRET_ID}/$VAULT_SECRET_ID/g" $CONFIGMAP_CHART_PATH/values.yaml
    - sed -i "s/\${K8S_MASTER_HOST_KEY}/$K8S_MASTER_HOST_KEY/g" $CONFIGMAP_CHART_PATH/values.yaml


    # for check
    - cat $CONFIGMAP_CHART_PATH/values.yaml

    - helm package $CONFIGMAP_CHART_PATH
    - helm upgrade --install "$CONFIGMAP_NAME" $CONFIGMAP_NAME-$CONFIGMAP_VERSION.tgz -f $CONFIGMAP_CHART_PATH/values.yaml -n "$NAMESPACE"
  environment:
    name: $ENV_SCOPE
