apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-terraman-api-deployment
  labels:
    app: terraman-api
  namespace: cp-terraman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-terraman-api
  template:
    metadata:
      labels:
        app: cp-terraman-api
    spec:
      containers:
        - name: cp-terraman-api
#          image: $REGISTRY_HARBOR_URL/container-platform-new-dev/container-platform-api:latest
          imange: registry.3.38.65.248.nip.io:5005/container-platform-v2/backend/terraman:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: K8S_API_SERVER
              value: "https://${K8S_MASTER_NODE_IP}:${K8S_API_SERVER_PORT}"
---
apiVersion: v1
kind: Service
metadata:
  name: cp-terraman-api-deployment
  labels:
    app: terraman-api
  namespace: cp-terraman-api
spec:
  ports:
    - nodePort: 32707
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cp-terraman-api
  type: NodePort
