apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-terraman-api-deployment
  labels:
    app: terraman-api
  namespace: cp-terraman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-terraman-api
  template:
    metadata:
      labels:
        app: cp-terraman-api
    spec:
      containers:
        - name: cp-terraman-api
#          image: $REGISTRY_HARBOR_URL/container-platform-new-dev/container-platform-api:latest
          image: registry.3.38.65.248.nip.io:5005/container-platform-v2/backend/terraman:{IMAGE_TAGS}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: K8S_API_SERVER
              value: "https://{K8S_MASTER_NODE_IP}:{K8S_API_SERVER_PORT}"
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: DATABASE_USER_ID
              value: ${DATABASE_USER_ID}
            - name: DATABASE_USER_PASSWORD
              value: ${DATABASE_USER_PASSWORD}
            - name: VAULT_IP
              value: {VAULT_IP}
            - name: VAULT_PORT
              value: {VAULT_PORT}
            - name: VAULT_ROLE_ID
              value: {VAULT_ROLE_ID}
            - name: VAULT_SECRET_ID
              value: {VAULT_SECRET_ID}
      imagePullSecrets:
        - name: {IMAGE_PULL_SECRET}
---
apiVersion: v1
kind: Service
metadata:
  name: cp-terraman-api-service
  labels:
    app: terraman-api
  namespace: cp-terraman
spec:
  ports:
    - nodePort: 32707
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cp-terraman-api
  type: NodePort
